site_name: UX Case Studies
site_url: https://studies.divstack.io
copyright: Copyright 2022


nav:
  - Home: index.md
  - Introduction: introduction.md
  - Project: project.md
extra_css:
    - css/custom.css
    - css/home.css
theme:
  name: material
  custom_dir: theme
  favicon: img/emblem.png
  logo: img/emblem.png
  font:
    text: Poppins
    code: Fira Mono
  features:
    - navigation.top
    - navigation.tabs
    # - navigation.tabs.sticky
    - search.share
    - search.suggest
    - toc.integrate
    - toc.follow
  palette:
    primary: 'indigo'
    accent: 'indigo'
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - toc:
      title: Table of Contents
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
plugins:
    - search
    - pdf-export:
        enabled_if_env: ENABLE_PDF_EXPORT
